### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by stone100010** [marrub--/zscript-doc#3]
// 分类列表
// [VarDef, CLASS(0), 'HEADS']
// [VarDef, CLASS(1), 'SHAPES']
// [VarDef, CLASS(2), 'FORMS']
// [VarDef, CLASS(3), 'DETAILS']
// [VarDef, CLASS(4), 'EMOTIONS']
// [VarDef, CLASS(5), 'CUSTOM']

[VarDef, HEADS(0), 'male']
[VarDef, HEADS(1), 'female']
[VarDef, HEADS(2), 'fat']
[VarDef, HEADS(3), 'skinny']
[VarDef, HEADS(4), 'old']
[VarDef, HEADS(5), 'young']
[VarDef, HEADS(6), 'primate']
[VarDef, HEADS(7), 'alien']

[VarDef, SHAPES(0), 'shape-wide']
[VarDef, SHAPES(1), 'shape-type']
[VarDef, SHAPES(2), 'braw_size']
[VarDef, SHAPES(3), 'chin_size']
[VarDef, SHAPES(4), 'ears-size']
[VarDef, SHAPES(5), 'eyes-size']
[VarDef, SHAPES(6), 'mouth-size']
[VarDef, SHAPES(7), 'mouse-size']

[VarDef, FORMS(0), 'ears_wide']
[VarDef, FORMS(1), 'ears-type']
[VarDef, FORMS(2), 'eyes_wide']
[VarDef, FORMS(3), 'eyes_type']
[VarDef, FORMS(4), 'mouth_wide']
[VarDef, FORMS(5), 'mouth_type']
[VarDef, FORMS(6), 'nouse_wide']
[VarDef, FORMS(7), 'nouse_type']

[VarDef, DETAILS(0), 'skin-a']
[VarDef, DETAILS(1), 'skin-b']
[VarDef, DETAILS(2), 'skin-c']
[VarDef, DETAILS(3), 'skin-d']
[VarDef, DETAILS(4), 'skin-e']
[VarDef, DETAILS(5), 'skin-f']
[VarDef, DETAILS(6), 'makeup']
[VarDef, DETAILS(7), 'beard']

[VarDef, EMOTIONS(0), 'close_eyes']
[VarDef, EMOTIONS(1), 'open_mouth']
[VarDef, EMOTIONS(2), 'disgust']
[VarDef, EMOTIONS(3), 'disappoint']
[VarDef, EMOTIONS(4), 'sadness']
[VarDef, EMOTIONS(5), 'smile']
[VarDef, EMOTIONS(6), 'enjoy']
[VarDef, EMOTIONS(7), 'angry']

[VarDef, CUSTOM(0), 'sculpt']
[VarDef, CUSTOM(1), '色彩']

// 2**10*42 = 1024 * 42 = 43008

// 循环
[Loop, 
	 [VarSize, 
	 	 CLASS
	 ], 
	 [Loop, 
	 	 [VarSize, 
	 	 	 HEADS
	 	 ], 
	 	 [Loop, 
	 	 	 [VarSize, 
	 	 	 	 SHAPES
	 	 	 ], 
	 	 	 [Loop, 
	 	 	 	 [VarSize, 
	 	 	 	 	 FORMS
	 	 	 	 ], 
	 	 	 	 [Loop, 
	 	 	 	 	 [VarSize, 
	 	 	 	 	 	 DETAILS
	 	 	 	 	 ], 
	 	 	 	 	 [Loop, 
	 	 	 	 	 	 [VarSize, 
	 	 	 	 	 	 	 EMOTIONS
	 	 	 	 	 	 ], 
	 	 	 	 	 	 [Loop, 
	 	 	 	 	 	 	 [VarSize, 
	 	 	 	 	 	 	 	 CUSTOM
	 	 	 	 	 	 	 ], 
	 	 	 	 	 	 	 [Note, CLASS(CLASSloopCount)]
	 	 	 	 	 	 	 [Note, HEADS(HEADSloopCount)]
	 	 	 	 	 	 	 [Note, SHAPES(SHAPESloopCount)]
	 	 	 	 	 	 	 [Note, FORMS(FORMSloopCount)]
	 	 	 	 	 	 	 [Note, DETAILS(DETAILSloopCount)]
	 	 	 	 	 	 	 [Note, EMOTIONS(EMOTIONSloopCount)]
	 	 	 	 	 	 	 [Note, CUSTOM(CUSTOMloopCount)]
	 	 	 	 	 	 	 , 
	 	 	 	 	 	 	 CUSTOMloopCount
	 	 	 	 	 	 ], 
	 	 	 	 	 	 EMOTIONSloopCount
	 	 	 	 	 ], 
	 	 	 	 	 DETAILSloopCount
	 	 	 	 ], 
	 	 	 	 FORMSloopCount
	 	 	 ], 
	 	 	 SHAPESloopCount
	 	 ], 
	 	 HEADSloopCount
	 ], 
	 CLASSloopCount
]

// 分类列表
// [VarDef, CLASS(0), 'HEADS']
// [VarDef, CLASS(1), 'SHAPES']
// [VarDef, CLASS(2), 'FORMS']
// [VarDef, CLASS(3), 'DETAILS']
// [VarDef, CLASS(4), 'EMOTIONS']
// [VarDef, CLASS(5), 'CUSTOM']

[VarDef, HEADS(0), 'male']
[VarDef, HEADS(1), 'female']
[VarDef, HEADS(2), 'fat']
[VarDef, HEADS(3), 'skinny']
[VarDef, HEADS(4), 'old']
[VarDef, HEADS(5), 'young']
[VarDef, HEADS(6), 'primate']
[VarDef, HEADS(7), 'alien']

[VarDef, SHAPES(0), 'shape-wide']
[VarDef, SHAPES(1), 'shape-type']
[VarDef, SHAPES(2), 'braw_size']
[VarDef, SHAPES(3), 'chin_size']
[VarDef, SHAPES(4), 'ears-size']
[VarDef, SHAPES(5), 'eyes-size']
[VarDef, SHAPES(6), 'mouth-size']
[VarDef, SHAPES(7), 'mouse-size']

[VarDef, FORMS(0), 'ears_wide']
[VarDef, FORMS(1), 'ears-type']
[VarDef, FORMS(2), 'eyes_wide']
[VarDef, FORMS(3), 'eyes_type']
[VarDef, FORMS(4), 'mouth_wide']
[VarDef, FORMS(5), 'mouth_type']
[VarDef, FORMS(6), 'nouse_wide']
[VarDef, FORMS(7), 'nouse_type']

[VarDef, DETAILS(0), 'skin-a']
[VarDef, DETAILS(1), 'skin-b']
[VarDef, DETAILS(2), 'skin-c']
[VarDef, DETAILS(3), 'skin-d']
[VarDef, DETAILS(4), 'skin-e']
[VarDef, DETAILS(5), 'skin-f']
[VarDef, DETAILS(6), 'makeup']
[VarDef, DETAILS(7), 'beard']

[VarDef, EMOTIONS(0), 'close_eyes']
[VarDef, EMOTIONS(1), 'open_mouth']
[VarDef, EMOTIONS(2), 'disgust']
[VarDef, EMOTIONS(3), 'disappoint']
[VarDef, EMOTIONS(4), 'sadness']
[VarDef, EMOTIONS(5), 'smile']
[VarDef, EMOTIONS(6), 'enjoy']
[VarDef, EMOTIONS(7), 'angry']

[VarDef, CUSTOM(0), 'sculpt']
[VarDef, CUSTOM(1), '色彩']

// 2**10*42 = 1024 * 42 = 43008

// 循环
[Loop, 
	 [VarSize, 
	 	 CLASS
	 ], 
	 [Loop, 
	 	 [VarSize, 
	 	 	 HEADS
	 	 ], 
	 	 [Loop, 
	 	 	 [VarSize, 
	 	 	 	 SHAPES
	 	 	 ], 
	 	 	 [Loop, 
	 	 	 	 [VarSize, 
	 	 	 	 	 FORMS
	 	 	 	 ], 
	 	 	 	 [Loop, 
	 	 	 	 	 [VarSize, 
	 	 	 	 	 	 DETAILS
	 	 	 	 	 ], 
	 	 	 	 	 [Loop, 
	 	 	 	 	 	 [VarSize, 
	 	 	 	 	 	 	 EMOTIONS
	 	 	 	 	 	 ], 
	 	 	 	 	 	 [Loop, 
	 	 	 	 	 	 	 [VarSize, 
	 	 	 	 	 	 	 	 CUSTOM
	 	 	 	 	 	 	 ], 
	 	 	 	 	 	 	 [Note, CLASS(CLASSloopCount)]
	 	 	 	 	 	 	 [Note, HEADS(HEADSloopCount)]
	 	 	 	 	 	 	 [Note, SHAPES(SHAPESloopCount)]
	 	 	 	 	 	 	 [Note, FORMS(FORMSloopCount)]
	 	 	 	 	 	 	 [Note, DETAILS(DETAILSloopCount)]
	 	 	 	 	 	 	 [Note, EMOTIONS(EMOTIONSloopCount)]
	 	 	 	 	 	 	 [Note, CUSTOM(CUSTOMloopCount)]
	 	 	 	 	 	 	 , 
	 	 	 	 	 	 	 CUSTOMloopCount
	 	 	 	 	 	 ], 
	 	 	 	 	 	 EMOTIONSloopCount
	 	 	 	 	 ], 
	 	 	 	 	 DETAILSloopCount
	 	 	 	 ], 
	 	 	 	 FORMSloopCount
	 	 	 ], 
	 	 	 SHAPESloopCount
	 	 ], 
	 	 HEADSloopCount
	 ], 
	 CLASSloopCount
]

**Comment by marrub--** [comment]
何？错误的地方？

**Comment by stone100010** [comment]
> 何？错误的地方？

There should be no problem with the script structure and no errors. I want to ask you if there is any simpler code.

**Comment by marrub--** [comment]
> > 何？错误的地方？
> 
> There should be no problem with the script structure and no errors. I want to ask you if there is any simpler code.

I... have no idea what your script is supposed to be for. This is completely unrelated to this project.
